### ISSUE TITLE
[Request] Telemetry

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/community#502] opened 2018-08-27 14:02 UTC
Can we have some usage statistics on how often our modules are downloads are being used? Either in terms of downloads, or preferably, in terms of actual usage of the modules inside of the Rack?

This would be super useful for knowing which modules are should be prioritized in terms of development.

**Comment by AndrewBelt** [comment] 2018-08-27 20:36
Duplicate of #226

**Closed by AndrewBelt** 2018-08-27 20:36 UTC
