### ISSUE TITLE
Future Request favorite list for plugins 

### ISSUE THREAD

**Issue by Klangspagat** [VCVRack/community#296] opened 2018-02-24 00:15 UTC
Could it be possible to add an favorite list for plugins instead of searching everytime thru the whole list to find the right plugin?
Greetings

**Comment by AndrewBelt** [comment] 2018-02-24 00:16
Rack feature requests go in this repo. https://github.com/VCVRack/Rack
Duplicate of https://github.com/VCVRack/Rack/issues/452

**Closed by AndrewBelt** 2018-02-24 00:16 UTC

**Comment by phdsg** [comment] 2018-02-24 00:17
wow your fast @AndrewBelt 
https://github.com/VCVRack/Rack/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+favorite
