### ISSUE TITLE
Is there any plan to show "date added" or "date updated" on the plugin manager page?

### ISSUE THREAD

**Issue by stutzjr** [VCVRack/community#417] opened 2018-04-02 01:27 UTC
Personally I don't like to be overwhelmed with too many module plugins all in one hit.
I try to keep my list short, and don't keep plugins I'm not expecting to use in the near future.
I don't mean to comment on the quality of other user's additions, I just want to focus on modules that suit my current usage - rather than "install everything" and then start picking favourites.
In my own time I continue to try other plugins but it's hard to keep track of where I'm up to.

Will there eventually be a way to highlight "what's new" or "what's been updated" from the plugin manager page?

**Comment by AndrewBelt** [comment] 2018-04-02 20:07
Duplicate of #266 
Added new thoughts to that issue.

**Closed by AndrewBelt** 2018-04-02 20:07 UTC
